#!/usr/bin/env bash
# roll-version.sh — create the next versioned calculator + docs pair.
#
# Usage:  roll-version.sh <app-version> [docs-version] [--date YYYY-MM-DD]
#
#   roll-version.sh 5.8          # app 5.7 -> 5.8, docs auto-bumped 1.1 -> 1.2
#   roll-version.sh 5.8 1.2      # both explicit
#   roll-version.sh 6.0 2.0 --date 2026-09-16   # deliberately restart the date prefix
#
# Does ONE thing: copies the newest HTML + docs to the next version and bumps
# every version string, verifying each replacement actually landed. It never
# overwrites an existing revision and never edits the harness, the docs prose,
# or git. Those are judgment calls — see SKILL.md.
set -euo pipefail

APP_NEW=""; DOCS_NEW=""; DATE_OVERRIDE=""
while [ $# -gt 0 ]; do
  case "$1" in
    --date) DATE_OVERRIDE="${2:-}"; shift 2 ;;
    -h|--help) sed -n '2,12p' "$0" | sed 's/^# \?//'; exit 0 ;;
    -*) echo "unknown flag: $1" >&2; exit 2 ;;
    *) if [ -z "$APP_NEW" ]; then APP_NEW="$1"
       elif [ -z "$DOCS_NEW" ]; then DOCS_NEW="$1"
       else echo "unexpected argument: $1" >&2; exit 2; fi; shift ;;
  esac
done

[ -n "$APP_NEW" ] || { echo "usage: roll-version.sh <app-version> [docs-version] [--date YYYY-MM-DD]" >&2; exit 2; }
[[ "$APP_NEW" =~ ^[0-9]+\.[0-9]+$ ]] || { echo "bad app version '$APP_NEW' (expected N.N)" >&2; exit 2; }
[ -z "$DOCS_NEW" ] || [[ "$DOCS_NEW" =~ ^[0-9]+\.[0-9]+$ ]] || { echo "bad docs version '$DOCS_NEW' (expected N.N)" >&2; exit 2; }
[ -z "$DATE_OVERRIDE" ] || [[ "$DATE_OVERRIDE" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]] || { echo "bad --date '$DATE_OVERRIDE'" >&2; exit 2; }

cd "$(git rev-parse --show-toplevel)"

HTML_OLD="$(ls simtlv_giga_calculator_generated_by_claude_*_v*.html 2>/dev/null \
  | sed -E 's/.*_v([0-9]+\.[0-9]+)\.html$/\1 &/' | sort -V | tail -1 | cut -d' ' -f2-)"
DOCS_OLD="$(ls simtlv_giga_calculator_docs_generated_by_claude_*_v*.md 2>/dev/null \
  | sed -E 's/.*_v([0-9]+\.[0-9]+)\.md$/\1 &/' | sort -V | tail -1 | cut -d' ' -f2-)"
[ -n "$HTML_OLD" ] || { echo "no calculator HTML found in $PWD" >&2; exit 1; }
[ -n "$DOCS_OLD" ] || { echo "no docs .md found in $PWD" >&2; exit 1; }

APP_OLD="$(sed -E 's/.*_v([0-9]+\.[0-9]+)\.html$/\1/' <<<"$HTML_OLD")"
DOCS_OLD_V="$(sed -E 's/.*_v([0-9]+\.[0-9]+)\.md$/\1/' <<<"$DOCS_OLD")"
# The date prefix is INHERITED from the source file so a chain stays consistent.
DATE_NEW="${DATE_OVERRIDE:-$(sed -E 's/.*_by_claude_([0-9]{4}-[0-9]{2}-[0-9]{2})_v.*/\1/' <<<"$HTML_OLD")}"
[ -n "$DOCS_NEW" ] || DOCS_NEW="${DOCS_OLD_V%.*}.$(( ${DOCS_OLD_V#*.} + 1 ))"

HTML_NEW="simtlv_giga_calculator_generated_by_claude_${DATE_NEW}_v${APP_NEW}.html"
DOCS_NEW_F="simtlv_giga_calculator_docs_generated_by_claude_${DATE_NEW}_v${DOCS_NEW}.md"

for t in "$HTML_NEW" "$DOCS_NEW_F"; do
  [ -e "$t" ] && { echo "REFUSING: $t already exists — never overwrite a revision" >&2; exit 1; }
done

echo "app  ${APP_OLD} -> ${APP_NEW}   docs ${DOCS_OLD_V} -> ${DOCS_NEW}   date ${DATE_NEW}"
cp "$HTML_OLD" "$HTML_NEW"
cp "$DOCS_OLD" "$DOCS_NEW_F"

FAIL=0
# sub <file> <label> <sed-expr> <required|optional> <literal string that must exist after>
sub() {
  sed -i -E "$3" "$1"
  if grep -qF "$5" "$1"; then echo "  ok   $2"
  elif [ "$4" = required ]; then echo "  FAIL $2 — pattern did not match, NOT bumped" >&2; FAIL=1
  else echo "  warn $2 — absent in this build (pre-convention?)" >&2; fi
}

sub "$HTML_NEW" "html header" \
  "s|Generated by Claude · [0-9]{4}-[0-9]{2}-[0-9]{2} · v[0-9]+\.[0-9]+|Generated by Claude · ${DATE_NEW} · v${APP_NEW}|g" \
  optional "Generated by Claude · ${DATE_NEW} · v${APP_NEW}"
sub "$HTML_NEW" "html MAIN SCRIPT banner" \
  "s|(MAIN SCRIPT — מחשבון גיגה )v[0-9]+\.[0-9]+|\1v${APP_NEW}|g" \
  optional "MAIN SCRIPT — מחשבון גיגה v${APP_NEW}"
sub "$DOCS_NEW_F" "docs header line" \
  "s|Generated by Claude · [0-9]{4}-[0-9]{2}-[0-9]{2} · v[0-9]+\.[0-9]+ · documents app version \*\*v[0-9]+\.[0-9]+\*\*|Generated by Claude · ${DATE_NEW} · v${DOCS_NEW} · documents app version **v${APP_NEW}**|" \
  required "· v${DOCS_NEW} · documents app version **v${APP_NEW}**"
sub "$DOCS_NEW_F" "docs companion filename" \
  "s|Companion file: \`simtlv_giga_calculator_generated_by_claude_[0-9-]+_v[0-9]+\.[0-9]+\.html\`|Companion file: \`${HTML_NEW}\`|" \
  required "Companion file: \`${HTML_NEW}\`"

if grep -qF "MAIN SCRIPT — מחשבון גיגה v${APP_OLD}" "$HTML_NEW" 2>/dev/null; then
  echo "  FAIL html still carries the old banner v${APP_OLD}" >&2; FAIL=1
fi
[ "$FAIL" -eq 0 ] || { echo "version roll INCOMPLETE — fix the above before writing any code" >&2; exit 1; }

cat <<NEXT

created:
  $HTML_NEW
  $DOCS_NEW_F

next:
  1. implement in $HTML_NEW
  2. extend tests/smoke.js  (stub branch + fix_* keys — see SKILL.md)
  3. node tests/smoke.js $HTML_NEW $HTML_OLD
  4. append the next "## NN. What changed in v${APP_NEW}" section to $DOCS_NEW_F
NEXT
